### ISSUE TITLE
Whitespace in literal(`|`) content is unexpectedly trimmed

### ISSUE THREAD

**Issue by kachick** [g-plane/pretty_yaml#1]
In v0.2.0

Input

```yaml
example: |
  foo
  bar  
  baz
```

Expected

```yaml
example: |
  foo
  bar  
  baz
```

Actual

```console
> dprint check
example.yml:
1 1| example:·|
2 2| ··foo
  3|-··bar··
3  |+··bar
4 4| ··baz
--
Found 1 not formatted file.
```

---

The line of `bar` includes whitespaces in the end of line, I expect that should be kept in [literal block](https://yaml.org/spec/1.2.2/#literal-style)

>Inside literal scalars, all ([indented](https://yaml.org/spec/1.2.2/#indentation-spaces)) characters are considered to be [content](https://yaml.org/spec/1.2.2/#nodes), including [white space](https://yaml.org/spec/1.2.2/#white-space-characters) characters. Note that all [line break](https://yaml.org/spec/1.2.2/#line-break-characters) characters are [normalized](https://yaml.org/spec/1.2.2/#line-break-characters). In addition, [empty lines](https://yaml.org/spec/1.2.2/#empty-lines) are not [folded](https://yaml.org/spec/1.2.2/#line-folding), though final [line breaks](https://yaml.org/spec/1.2.2/#line-break-characters) and trailing [empty lines](https://yaml.org/spec/1.2.2/#empty-lines) are [chomped](https://yaml.org/spec/1.2.2/#block-chomping-indicator).

**Comment by g-plane** [comment]
Can you provide any cases about trailing whitespaces should be kept?

**Comment by kachick** [comment]
I currently don't have a specific use case for that. However, I prefer not to alter the semantics by employing formatters.

**Comment by g-plane** [comment]
I think we can add an option called `trimTrailingWhitespace`. Default value will be `true`. By disabling this option you can keep trailing whitespaces.

**Comment by kachick** [comment]
Sure! I'll disable the flag. Thanks for your consideration 🙏 

As I understand it, the flag is similar to that recently added by yamlfmt: https://github.com/google/yamlfmt/commit/e003da670786b8fb39fe994f1730ad6ab5b3a757

**Comment by g-plane** [comment]
Yes. I'm inspired by yamlfmt.

**Comment by kachick** [comment]
Thank you!
